### ISSUE TITLE
在 GCC 6.1 上编译失败

### ISSUE THREAD

**Issue by pingplug** [HomeOfVapourSynthEvolution/VapourSynth-CTMF#3]
貌似 ceil 是在 cmath 里的

    CTMF/CTMF.cpp: 在函数‘const VSFrameRef* ctmfGetFrame(int, int, void**, void**, VSFrameContext*, VSCore*, const VSAPI*)’中:
    CTMF/CTMF.cpp:211:58: 错误：‘ceil’不是‘std’的成员
                         const int stripes = static_cast<int>(std::ceil(static_cast<double>(width - 2 * d->radius) / (d->memsize / sizeof(Histogram<16>) - 2 * d->radius)));
                                                              ^~~
    GNUmakefile:23: recipe for target 'CTMF/CTMF.o' failed
    make: *** [CTMF/CTMF.o] Error 1

**Comment by RoyiAvital** [comment]
@HolyWu , Any way to contact you over email?
