### ISSUE TITLE
Any radius other than 2 crashes

### ISSUE THREAD

**Issue by Selur** [HomeOfVapourSynthEvolution/VapourSynth-CTMF#5]
Using YV12 input and using anything other than radius = 2 crashes.

**Comment by HolyWu** [comment]
What's your CPU? Probably the same as https://github.com/HomeOfVapourSynthEvolution/VapourSynth-CTMF/issues/4. Does it still crash if you specify `opt=2 or 3`?

**Comment by Selur** [comment]
I'm using a AMD Ryzen 9 7950X.
You are right it's probably the same using opt=2, and opt=3 both work fine.
Thanks!
